### ISSUE TITLE
Can't load anything

### ISSUE THREAD

**Issue by gdfzsmf09** [bugdone/headshotbox#14]
2015-May-09 01:52:13 +0800 Christian DEBUG [hsbox.indexer] - Indexer started
2015-May-09 01:52:13 +0800 Christian DEBUG [hsbox.indexer] - Adding path F:\Stea
mLibrary\SteamApps\common\Counter-Strike Global Offensive\csgo\replays\match730_
003043633831350370315_0681149064_900.dem
2015-May-09 01:52:14 +0800 Christian INFO [hsbox.demo] - Processing F:\SteamLibr
ary\SteamApps\common\Counter-Strike Global Offensive\csgo\replays\match730_00304
3633831350370315_0681149064_900.dem
Exception in thread "main" java.lang.AssertionError: Assert failed: (zero? (:exi
t proc))
        at hsbox.demo$parse_demo.invoke(demo.clj:37)
        at hsbox.demo$get_demo_info.invoke(demo.clj:85)
        at hsbox.indexer$add_demo.invoke(indexer.clj:48)
        at hsbox.indexer$run.invoke(indexer.clj:86)
        at hsbox.core$_main.doInvoke(core.clj:34)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at hsbox.core.main(Unknown Source)
2015-05-09 01:52:14.818:WARN:oejs.AbstractHttpConnection:/api/steamids/info?stea
mids=
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at java.lang.Long.parseLong(Unknown Source)
        at hsbox.steamapi$get_steamids_info$fn__7458.invoke(steamapi.clj:34)
        at clojure.core$map$fn__4245.invoke(core.clj:2557)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.LazySeq.first(LazySeq.java:71)
        at clojure.lang.RT.first(RT.java:577)
        at clojure.core$first.invoke(core.clj:55)
        at clojure.string$join.invoke(string.clj:185)
        at hsbox.db$get_steamid_info.invoke(db.clj:119)
        at hsbox.steamapi$get_steamids_info.invoke(steamapi.clj:37)
        at hsbox.handler$fn__8433.invoke(handler.clj:39)
        at compojure.core$make_route$fn__1390.invoke(core.clj:113)
        at compojure.core$wrap_route_middleware$fn__1386.invoke(core.clj:103)
        at compojure.core$if_route$fn__1369.invoke(core.clj:41)
        at compojure.core$if_method$fn__1361.invoke(core.clj:27)
        at compojure.core$routing$fn__1396.invoke(core.clj:127)
        at clojure.core$some.invoke(core.clj:2515)
        at compojure.core$routing.doInvoke(core.clj:127)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:626)
        at compojure.core$routes$fn__1400.invoke(core.clj:132)
        at ring.middleware.json$wrap_json_response$fn__8410.invoke(json.clj:65)
        at ring.middleware.json$wrap_json_body$fn__8393.invoke(json.clj:35)
        at ring.middleware.cors$wrap_cors$fn__8377.invoke(cors.clj:150)
        at compojure.core$routing$fn__1396.invoke(core.clj:127)
        at clojure.core$some.invoke(core.clj:2515)
        at compojure.core$routing.doInvoke(core.clj:127)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at hsbox.handler$fn__8456.invoke(handler.clj:66)
        at compojure.core$if_context$fn__1418.invoke(core.clj:198)
        at compojure.core$routing$fn__1396.invoke(core.clj:127)
        at clojure.core$some.invoke(core.clj:2515)
        at compojure.core$routing.doInvoke(core.clj:127)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:626)
        at compojure.core$routes$fn__1400.invoke(core.clj:132)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__1519.invoke(ke
yword_params.clj:35)
        at ring.middleware.nested_params$wrap_nested_params$fn__1562.invoke(nest
ed_params.clj:84)
        at ring.middleware.params$wrap_params$fn__1492.invoke(params.clj:64)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__1598.invok
e(multipart_params.clj:118)
        at ring.middleware.flash$wrap_flash$fn__2272.invoke(flash.clj:35)
        at ring.middleware.session$wrap_session$fn__2259.invoke(session.clj:98)
        at clojure.lang.Var.invoke(Var.java:379)
        at ring.adapter.jetty$proxy_handler$fn__8518.invoke(jetty.clj:20)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHan
dler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(Abstrac
tHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(Abstra
ctHttpConnection.java:933)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.header
Complete(AbstractHttpConnection.java:995)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)

        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnecti
on.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEn
dPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEnd
Point.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:543)
        at java.lang.Thread.run(Unknown Source)

**Comment by bugdone** [comment]
Try installing http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe

**Comment by gdfzsmf09** [comment]
Pretty much fixed the problem. Thanks man! Nice work! :+1:
