### ISSUE TITLE
OpenID Realm with https

### ISSUE THREAD

**Issue by Arendt** [bugdone/headshotbox#141]
I cant use headshotbox with a subdomain and https.

## The error message: 

Mrz 18, 2016 2:02:48 AM org.openid4java.discovery.Discovery discover
INFORMATION: Starting discovery on URL identifier: http://steamcommunity.com/openid
Mrz 18, 2016 2:02:49 AM org.openid4java.discovery.yadis.YadisResolver discover
INFORMATION: Yadis discovered 1 endpoints from: http://steamcommunity.com/openid
Mrz 18, 2016 2:02:49 AM org.openid4java.discovery.Discovery discover
INFORMATION: Discovered 1 OpenID endpoints.
Mrz 18, 2016 2:02:49 AM org.openid4java.consumer.ConsumerManager associate
WARNUNG: Association failed; using first entry: https://steamcommunity.com/openid/login
Mrz 18, 2016 2:02:49 AM org.openid4java.consumer.ConsumerManager authenticate
INFORMATION: Creating authentication request for OP-endpoint: https://steamcommunity.com/openid/login claimedID: http://specs.openid.net/auth/2.0/identifier_select OP-specific ID: http://specs.openid.net/auth/2.0/identifier_select
Mrz 18, 2016 2:02:49 AM org.openid4java.server.RealmVerifier validate
SCHWERWIEGEND: Return URL: http://127.0.0.1:4000/openid does not match realm: https://hsb.my.domain.org
2016-Mrz-18 02:02:49 +0100 my-domain.org ERROR [hsbox.handler] -
                                                                     java.lang.Thread.run                  Thread.java:  745
                                     org.eclipse.jetty.util.thread.QueuedThreadPool$3.run        QueuedThreadPool.java:  543
                                    org.eclipse.jetty.util.thread.QueuedThreadPool.runJob        QueuedThreadPool.java:  608
                                     org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run   SelectChannelEndPoint.java:   52
                                    org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle   SelectChannelEndPoint.java:  668
                                      org.eclipse.jetty.server.AsyncHttpConnection.handle     AsyncHttpConnection.java:   82
                                         org.eclipse.jetty.http.HttpParser.parseAvailable              HttpParser.java:  240
                                              org.eclipse.jetty.http.HttpParser.parseNext              HttpParser.java:  865
                   org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content  AbstractHttpConnection.java: 1005
                                  org.eclipse.jetty.server.AbstractHttpConnection.content  AbstractHttpConnection.java:  944
                            org.eclipse.jetty.server.AbstractHttpConnection.handleRequest  AbstractHttpConnection.java:  486
                                                   org.eclipse.jetty.server.Server.handle                  Server.java:  369
                                   org.eclipse.jetty.server.handler.HandlerWrapper.handle          HandlerWrapper.java:  116
ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle
                                                      ring.adapter.jetty/proxy-handler/fn                    jetty.clj:   20
                                                  ring.middleware.session/wrap-session/fn                  session.clj:   98
                                                      ring.middleware.flash/wrap-flash/fn                    flash.clj:   35
                                ring.middleware.multipart-params/wrap-multipart-params/fn         multipart_params.clj:  118
                                                    ring.middleware.params/wrap-params/fn                   params.clj:   64
                                      ring.middleware.nested-params/wrap-nested-params/fn            nested_params.clj:   84
                                    ring.middleware.keyword-params/wrap-keyword-params/fn           keyword_params.clj:   35
                                                          hsbox.handler/wrap-exception/fn                  handler.clj:  132
                                                          cemerick.friend/authenticate/fn                   friend.clj:  260
                                                            cemerick.friend/authenticate*                   friend.clj:  247
                                                     cemerick.friend/authenticate-request                   friend.clj:  238
                                                                        clojure.core/some                     core.clj: 2515
                                                  cemerick.friend/authenticate-request/fn                   friend.clj:  238
                                                       cemerick.friend.openid/workflow/fn                   openid.clj:  118
                                                       cemerick.friend.openid/handle-init                   openid.clj:   54
                                                                                      ...
                                    org.openid4java.consumer.ConsumerManager.authenticate         ConsumerManager.java: 1071
                                    org.openid4java.message.AuthRequest.createAuthRequest             AuthRequest.java:  101
                                             org.openid4java.message.AuthRequest.validate             AuthRequest.java:  354
org.openid4java.message.MessageException: 0x301: Realm verification failed (5) for: https://hsb.my-domain.org
    errorCode: 769

2016-03-18 02:02:49.525:WARN:oejs.AbstractHttpConnection:/openid
org.openid4java.message.MessageException: 0x301: Realm verification failed (5) for: https://hsb.my-domain.org
        at org.openid4java.message.AuthRequest.validate(AuthRequest.java:354)
        at org.openid4java.message.AuthRequest.createAuthRequest(AuthRequest.java:101)
        at org.openid4java.consumer.ConsumerManager.authenticate(ConsumerManager.java:1071)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at cemerick.friend.openid$handle_init.invoke(openid.clj:54)
        at cemerick.friend.openid$workflow$fn__9452.invoke(openid.clj:118)
        at cemerick.friend$authenticate_request$fn__9003.invoke(friend.clj:238)
        at clojure.core$some.invoke(core.clj:2515)
        at cemerick.friend$authenticate_request.invoke(friend.clj:238)
        at cemerick.friend$authenticate_STAR_.invoke(friend.clj:247)
        at cemerick.friend$authenticate$fn__9013.invoke(friend.clj:260)
        at hsbox.handler$wrap_exception$fn__9557.invoke(handler.clj:132)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__1519.invoke(keyword_params.clj:35)
        at ring.middleware.nested_params$wrap_nested_params$fn__1562.invoke(nested_params.clj:84)
        at ring.middleware.params$wrap_params$fn__1492.invoke(params.clj:64)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__1598.invoke(multipart_params.clj:118)
        at ring.middleware.flash$wrap_flash$fn__2272.invoke(flash.clj:35)
        at ring.middleware.session$wrap_session$fn__2259.invoke(session.clj:98)
        at ring.adapter.jetty$proxy_handler$fn__9641.invoke(jetty.clj:20)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:944)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1005)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

## My apache config:

<VirtualHost *:443>
ServerName hsb.my-domain.org
SSLEngine on
SSLCertificateFile cert/path/
SSLCertificateKeyFile cert/path/
SSLProtocol all -SSLv2 -SSLv3
SSlCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
  SSLHonorCipherOrder on
  Header always set Strict-Transport-Security "max-age=31536000"
    <Location />
        ProxyPass http://127.0.0.1:4000/
        ProxyPassReverse http://127.0.0.1:4000/
        Order allow,deny
        Allow from all
    </Location>
</VirtualHost>

**Comment by tabakhase** [comment]
Works fine behind my Nginx with the following settings:
`		proxy_set_header Host              $host;`
`		proxy_set_header x-real-ip         $remote_addr;`
`		proxy_set_header x-forwarded-for   $proxy_add_x_forwarded_for;`
`		proxy_set_header x-forwarded-host  $host;`
`		proxy_set_header x-forwarded-proto $scheme;`
`		proxy_set_header x-forwarded-port  $server_port;`

**Comment by Arendt** [comment]
How can i set the Return URL: http://127.0.0.1:4000/openid to my subdomain?

i think thats the problem:

AM org.openid4java.server.RealmVerifier validate
CRITICAL: Return URL: http://127.0.0.1:4000/openid does not match realm: https://hsb.my.domain.org

My headshotbox.sh:

java -jar hsbox-0.11.0-standalone.jar --port 4000 --admin-steamid 765xxxxxxxxxxxxx --openid-realm https://hsb.my-domain.org

**Comment by tabakhase** [comment]
see above.
Copy&adapt my nginx headers for your apache, the rest should happen automatically.

**Comment by Arendt** [comment]
This apache config is working now:

<VirtualHost *:443>
	ServerName hsb.my-domain.org
	SSLEngine on
	SSLCertificateFile /etc/path
	SSLCertificateKeyFile /etc/path
	SSLProtocol all -SSLv2 -SSLv3
	SSlCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA;
	SSLHonorCipherOrder on
	Header always set Strict-Transport-Security "max-age=31536000"
	ProxyPreserveHost On
   
        RequestHeader set Host "hsb.my-domain.org"
	RequestHeader set x-real-ip $remote_addr
	RequestHeader set x-forwarded-for $proxy_add_x_forwarded_for
	RequestHeader set x-forwarded-host "hsb.my-domain.org"
	RequestHeader set x-forwarded-proto "https"
	RequestHeader set x-forwarded-port "443"

	<Location />
		ProxyPass http://127.0.0.1:4000/
                ProxyPassReverse http://127.0.0.1:4000/
                Order allow,deny
                Allow from all
    </Location>
   
</VirtualHost>
