### ISSUE TITLE
Problem running the Linux build in docker, on Ubuntu

### ISSUE THREAD

**Issue by yoyosan** [bugdone/headshotbox#26]
Hello.

I've built a [docker container](https://github.com/yoyosan/docker-headshot-box) for this application, but when running it I have this problem:

```
root@a1404479fa95:~/hsbox# ./headshotbox.sh 
Exception in thread "main" java.lang.UnsupportedClassVersionError: Cstrike15Gcmessages$CDataGCCStrike15_v2_MatchInfo : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at hsbox.demo__init.__init0(Unknown Source)
	at hsbox.demo__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at hsbox.indexer$loading__4958__auto__.invoke(indexer.clj:1)
	at hsbox.indexer__init.load(Unknown Source)
	at hsbox.indexer__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:1096)
	at hsbox.handler$loading__4958__auto__.invoke(handler.clj:1)
	at hsbox.handler__init.load(Unknown Source)
	at hsbox.handler__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at hsbox.core$loading__4958__auto__.invoke(core.clj:1)
	at hsbox.core__init.load(Unknown Source)
	at hsbox.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:2093)
	at clojure.lang.RT.load(RT.java:430)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at hsbox.core.<clinit>(Unknown Source)
```

Java version:
```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by yoyosan** [comment]
Running from Arch Linux works just fine, but:

```
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by yoyosan** [comment]
I've updated to Java 8 but I get the following error:
```
hsbox_1 | 2015-May-10 17:41:47 +0000 78f3bbd4a44b INFO [hsbox.demo] - Processing /root/hsbox/demos/match730_003072359109496930670_0183010677_134.dem
hsbox_1 | 2015-May-10 17:41:47 +0000 78f3bbd4a44b ERROR [hsbox.indexer] - Cannot parse demo /root/hsbox/demos/match730_003072359109496930670_0183010677_134.dem #<IOException java.io.IOException: Cannot run program "/root/hsbox/demoinfogo": error=2, No such file or directory>
```

**Comment by yoyosan** [comment]
```
ldd demoinfogo 
	not a dynamic executable
```

**Comment by yoyosan** [comment]
I've found the issue: http://stackoverflow.com/questions/2716702/no-such-file-or-directory-error-when-executing-a-binary

**Comment by yoyosan** [comment]
Works flawlessly, yay!

**Comment by abenea** [comment]
1. Java 1.7 should be enough, this is probably a problem with the build scripts.
2. How did you fix the second issue? This probably needs to go into the list of requirements.

**Comment by yoyosan** [comment]
```
sudo apt-get install -y libc6-i386
```

I'll commit after I do some more tests.

**Comment by yoyosan** [comment]
@abenea Java 7 will no longer be maintained by Oracle.

**Comment by nahtnam** [comment]
Same issue. Whats the solution?

**Comment by yoyosan** [comment]
@nahtnam 
1. Upgrade to Java 8 using http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
2. Install:
```
sudo apt-get install -y libc6-i386
```

**Comment by bugdone** [comment]
I re-uploaded the binary for linux, should work with java 7 now.

**Comment by yoyosan** [comment]
I'll test this evening.

Cheers.

**Comment by yoyosan** [comment]
All fine.
